export const DECENT_TEAM = [
  {
    name: "Fighter",
    hit_points: 10,
    strength: 15,
    dexterity: 10,
    constitution: 14,
    intelligence: 8,
    wisdom: 12,
    charisma: 12,
  },
  {
    name: "Rogue",
    hit_points: 8,
    strength: 10,
    dexterity: 16,
    constitution: 12,
    intelligence: 12,
    wisdom: 14,
    charisma: 10,
  },
  {
    name: "Wizard",
    hit_points: 6,
    strength: 8,
    dexterity: 12,
    constitution: 10,
    intelligence: 16,
    wisdom: 14,
    charisma: 12,
  },
];

export const GREAT_TEAM = [
  {
    name: "Fighter",
    hit_points: 25,
    strength: 17,
    dexterity: 14,
    constitution: 16,
    intelligence: 10,
    wisdom: 14,
    charisma: 14,
  },
  {
    name: "Rogue",
    hit_points: 20,
    strength: 12,
    dexterity: 18,
    constitution: 14,
    intelligence: 14,
    wisdom: 16,
    charisma: 12,
  },
  {
    name: "Wizard",
    hit_points: 15,
    strength: 10,
    dexterity: 14,
    constitution: 12,
    intelligence: 18,
    wisdom: 16,
    charisma: 14,
  },
];

export const BADASS_TEAM = [
  {
    name: "Fighter",
    hit_points: 45,
    strength: 20,
    dexterity: 16,
    constitution: 18,
    intelligence: 12,
    wisdom: 16,
    charisma: 16,
  },
  {
    name: "Rogue",
    hit_points: 35,
    strength: 14,
    dexterity: 20,
    constitution: 16,
    intelligence: 16,
    wisdom: 18,
    charisma: 14,
  },
  {
    name: "Wizard",
    hit_points: 25,
    strength: 12,
    dexterity: 16,
    constitution: 14,
    intelligence: 20,
    wisdom: 18,
    charisma: 16,
  },
];
